window.berExtraQuestions = [
  {q:"Saya ___ di Jakarta.",a:"ber tinggal",c:["ber tinggal","men tinggal","di tinggal","ke tinggal"],e:"ber- + tinggal = bertinggal（住む）。実際は tinggal だけでもよく使います。"},
  {q:"Mereka ___ di kantor.",a:"bekerja",c:["bekerja","berkerja","memkerja","dikerja"],e:"ber- + kerja は bekerja（働く）。"},
  {q:"Dia ___ sepeda ke sekolah.",a:"bersepeda",c:["bersepeda","menyepeda","berjalan","bermain"],e:"bersepeda = 自転車に乗る。"},
  {q:"Kami ___ bahasa Indonesia.",a:"belajar",c:["belajar","berajar","mengajar","diajar"],e:"belajar = 勉強する。ber + ajar の特殊形。"},
  {q:"Anak-anak ___ bola di taman.",a:"bermain",c:["bermain","memain","berbola","dibermain"],e:"bermain = 遊ぶ。bermain bola = ボールで遊ぶ。"},
  {q:"Saya ___ pagi setiap hari.",a:"berolahraga",c:["berolahraga","mengolahraga","diolahraga","berlari"],e:"berolahraga = 運動する。"},
  {q:"Dia ___ merah hari ini.",a:"berbaju",c:["berbaju","memakai","berwarna","bertopi"],e:"berbaju merah = 赤い服を着ている。"},
  {q:"Ibu ___ di dapur.",a:"memasak",c:["memasak","bermasak","dimasak","pemasak"],e:"料理するは biasanya memasak。bermasak は一般的ではありません。"},
  {q:"Mereka ___ tentang ujian.",a:"berbicara",c:["berbicara","membicara","dibicara","berkata"],e:"berbicara tentang = 〜について話す。"},
  {q:"Saya ___ kepada guru.",a:"bertanya",c:["bertanya","menanya","ditanya","pertanyaan"],e:"bertanya kepada = 〜に質問する。"},
  {q:"Dia ___ karena senang.",a:"tertawa",c:["tertawa","bertawa","menawa","ditawa"],e:"笑うは tertawa。ber-ではありません。"},
  {q:"Kami ___ di rumah.",a:"beristirahat",c:["beristirahat","mengistirahat","diistirahat","istirahatkan"],e:"beristirahat = 休む。"},
  {q:"Mereka ___ di ruang makan.",a:"berkumpul",c:["berkumpul","mengumpul","dikumpul","kumpulan"],e:"berkumpul = 集まる。"},
  {q:"Saya ___ dengan teman.",a:"bertemu",c:["bertemu","menemu","ditemu","pertemuan"],e:"bertemu dengan = 〜と会う。"},
  {q:"Dia ___ ke kantor.",a:"berjalan kaki",c:["berjalan kaki","menjalan kaki","berlari kaki","dijalan kaki"],e:"berjalan kaki = 歩いて行く。"},
  {q:"Kami ___ di masjid.",a:"berdoa",c:["berdoa","mendoa","didoa","doakan"],e:"berdoa = 祈る。"},
  {q:"Mereka ___ di restoran.",a:"makan",c:["makan","bermakan","memakan","dimakan"],e:"食べるは基本 makan。bermakan は通常使いません。"},
  {q:"Saya ___ topi.",a:"bertopi",c:["bertopi","mentopi","ditopi","topikan"],e:"bertopi = 帽子をかぶっている。"},
  {q:"Dia ___ kacamata.",a:"berkacamata",c:["berkacamata","memkacamata","dikacamata","bermata"],e:"berkacamata = 眼鏡をかけている。"},
  {q:"Kami ___ rencana liburan.",a:"berencana",c:["berencana","merencana","direncana","perencana"],e:"berencana = 計画する。"},
  {q:"Saya ___ saudara dua orang.",a:"bersaudara",c:["bersaudara","mensaudara","disaudara","saudaraan"],e:"bersaudara dua orang = 兄弟が2人いる。"},
  {q:"Dia ___ anak satu.",a:"beranak",c:["beranak","menganak","dianak","anak-anak"],e:"beranak satu = 子どもが1人いる。"},
  {q:"Rumah itu ___ halaman luas.",a:"berhalaman",c:["berhalaman","menghalaman","dihalaman","halaman"],e:"berhalaman luas = 広い庭がある。"},
  {q:"Mobil itu ___ warna hitam.",a:"berwarna",c:["berwarna","mewarna","diwarna","pewarna"],e:"berwarna hitam = 黒色である。"},
  {q:"Kami ___ bersama.",a:"bekerja sama",c:["bekerja sama","berkerja sama","mengerja sama","dikerja sama"],e:"bekerja sama = 協力する。"},
  {q:"Dia ___ di depan kelas.",a:"berdiri",c:["berdiri","mendiri","didiri","pendiri"],e:"berdiri = 立つ。"},
  {q:"Saya ___ di kursi.",a:"duduk",c:["duduk","berduduk","menduduk","diduduk"],e:"座るは duduk。berduduk は通常使いません。"},
  {q:"Mereka ___ lagu Indonesia.",a:"bernyanyi",c:["bernyanyi","menyanyi","dinyanyi","penyanyi"],e:"bernyanyi/menyanyi = 歌う。E級では bernyanyi を覚える。"},
  {q:"Dia ___ gitar.",a:"bermain",c:["bermain","memainkan","bergitar","digitar"],e:"bermain gitar = ギターを弾く。"},
  {q:"Kami ___ di hotel.",a:"bermalam",c:["bermalam","memalam","dipalam","malamkan"],e:"bermalam = 泊まる。"},
  {q:"Saya ___ kepada orang tua.",a:"berbakti",c:["berbakti","membakti","dibakti","pembakti"],e:"berbakti kepada = 〜に尽くす。"},
  {q:"Dia ___ hati-hati.",a:"berjalan",c:["berjalan","menjalan","dijalan","perjalanan"],e:"berjalan = 歩く／進む。"},
  {q:"Mereka ___ di laut.",a:"berenang",c:["berenang","menenang","dienang","renang"],e:"berenang = 泳ぐ。"},
  {q:"Saya ___ dengan keluarga.",a:"berlibur",c:["berlibur","melibur","dilibur","liburan"],e:"berlibur = 休暇を過ごす。"},
  {q:"Dia ___ di pasar.",a:"berbelanja",c:["berbelanja","membelanja","dibelanja","belanjaan"],e:"berbelanja = 買い物する。"},
  {q:"Kami ___ di kelas.",a:"berdiskusi",c:["berdiskusi","mendiskusi","didiskusi","diskusikan"],e:"berdiskusi = 話し合う。"},
  {q:"Saya ___ di universitas.",a:"berkuliah",c:["berkuliah","mengkuliah","dikuliah","perkuliahan"],e:"berkuliah = 大学で学ぶ。"},
  {q:"Mereka ___ saat pesta.",a:"bergembira",c:["bergembira","menggembira","digembira","gembirakan"],e:"bergembira = 喜ぶ。"},
  {q:"Dia ___ dengan sopan.",a:"berbicara",c:["berbicara","membicara","dibicara","pembicara"],e:"berbicara dengan sopan = 丁寧に話す。"},
  {q:"Saya ___ nomor telepon.",a:"mempunyai",c:["mempunyai","berpunya","dipunya","punyai"],e:"持っているは mempunyai / punya。berpunya は基本使いません。"}
];
window.conversation2Questions = [
  {q:"A: Apa kabar? B: ___",a:"Baik-baik saja.",c:["Baik-baik saja.","Selamat pagi.","Terima kasih kembali.","Sampai jumpa."],e:"Apa kabar? = 元気ですか。返答は Baik-baik saja."},
  {q:"A: Siapa nama Anda? B: ___",a:"Nama saya Sari.",c:["Nama saya Sari.","Saya dari Jepang.","Saya mau makan.","Ini buku."],e:"名前を聞かれているので Nama saya..."},
  {q:"A: Dari mana Anda? B: ___",a:"Saya dari Jepang.",c:["Saya dari Jepang.","Saya guru.","Saya belajar.","Saya ke kantor."],e:"Dari mana = どこから。"},
  {q:"A: Mau ke mana? B: ___",a:"Saya mau ke pasar.",c:["Saya mau ke pasar.","Saya dari rumah.","Saya makan nasi.","Saya sudah tidur."],e:"Mau ke mana = どこへ行きたい/行くところですか。"},
  {q:"A: Terima kasih. B: ___",a:"Sama-sama.",c:["Sama-sama.","Maaf.","Silakan.","Apa kabar?"],e:"ありがとうへの返事は Sama-sama."},
  {q:"A: Maaf. B: ___",a:"Tidak apa-apa.",c:["Tidak apa-apa.","Selamat malam.","Saya lapar.","Ini mahal."],e:"謝罪への返答は Tidak apa-apa."},
  {q:"A: Permisi. B: ___",a:"Silakan.",c:["Silakan.","Tidak tahu.","Sampai besok.","Enak sekali."],e:"Permisi に対して Silakan = どうぞ。"},
  {q:"A: Berapa harganya? B: ___",a:"Sepuluh ribu rupiah.",c:["Sepuluh ribu rupiah.","Jam tujuh.","Di sebelah kanan.","Saya guru."],e:"Harga = 値段。金額で答える。"},
  {q:"A: Jam berapa sekarang? B: ___",a:"Jam delapan.",c:["Jam delapan.","Delapan orang.","Delapan hari.","Delapan buku."],e:"Jam berapa = 何時。"},
  {q:"A: Di mana toilet? B: ___",a:"Di sebelah kiri.",c:["Di sebelah kiri.","Saya dari Tokyo.","Besok pagi.","Makan nasi."],e:"Di mana = どこ。場所で答える。"},
  {q:"A: Apakah ini buku Anda? B: ___",a:"Ya, ini buku saya.",c:["Ya, ini buku saya.","Saya pergi.","Tidak mahal.","Jam tiga."],e:"Apakah ini...? = これは〜ですか。"},
  {q:"A: Anda suka kopi? B: ___",a:"Ya, saya suka kopi.",c:["Ya, saya suka kopi.","Saya dari kantor.","Di meja.","Hari Senin."],e:"suka = 好き。"},
  {q:"A: Sudah makan? B: ___",a:"Sudah.",c:["Sudah.","Di sana.","Siapa?","Berapa?"],e:"Sudah makan? = もう食べましたか。"},
  {q:"A: Belum tidur? B: ___",a:"Belum.",c:["Belum.","Terima kasih.","Di rumah sakit.","Saya Jepang."],e:"Belum = まだ。"},
  {q:"A: Boleh saya masuk? B: ___",a:"Boleh.",c:["Boleh.","Tidak punya.","Kemarin.","Murah."],e:"Boleh = 〜してよい。"},
  {q:"A: Bisa bantu saya? B: ___",a:"Bisa.",c:["Bisa.","Mahal.","Pagi.","Dari mana."],e:"Bisa bantu saya? = 手伝ってもらえますか。"},
  {q:"A: Ini apa? B: ___",a:"Ini kamus.",c:["Ini kamus.","Saya sehat.","Ke sekolah.","Jam lima."],e:"Ini apa? = これは何ですか。"},
  {q:"A: Itu siapa? B: ___",a:"Itu teman saya.",c:["Itu teman saya.","Itu besar.","Itu murah.","Itu pagi."],e:"Siapa = 誰。"},
  {q:"A: Kapan ujian? B: ___",a:"Besok pagi.",c:["Besok pagi.","Di kelas.","Dengan teman.","Seratus rupiah."],e:"Kapan = いつ。"},
  {q:"A: Mengapa terlambat? B: ___",a:"Karena jalan macet.",c:["Karena jalan macet.","Di rumah.","Jam satu.","Buku saya."],e:"Mengapa/Kenapa = なぜ。Karena = なぜなら。"},
  {q:"A: Bagaimana rasanya? B: ___",a:"Enak sekali.",c:["Enak sekali.","Di sana.","Besok.","Lima orang."],e:"Bagaimana rasanya = 味はどうですか。"},
  {q:"A: Mau minum apa? B: ___",a:"Saya mau minum air.",c:["Saya mau minum air.","Saya dari air.","Saya pergi air.","Saya membaca air."],e:"Mau minum apa = 何を飲みたいですか。"},
  {q:"A: Mau makan apa? B: ___",a:"Saya mau makan nasi goreng.",c:["Saya mau makan nasi goreng.","Saya mau tidur nasi goreng.","Saya dari nasi goreng.","Saya ke nasi goreng."],e:"makan = 食べる。"},
  {q:"A: Anda tinggal di mana? B: ___",a:"Saya tinggal di Tokyo.",c:["Saya tinggal di Tokyo.","Saya pergi Tokyo.","Saya dari makan.","Saya mahal."],e:"tinggal di = 〜に住む。"},
  {q:"A: Hari ini hari apa? B: ___",a:"Hari ini hari Senin.",c:["Hari ini hari Senin.","Hari ini jam dua.","Hari ini mahal.","Hari ini di meja."],e:"hari apa = 何曜日。"},
  {q:"A: Besok hari apa? B: ___",a:"Besok hari Selasa.",c:["Besok hari Selasa.","Besok jam buku.","Besok murah.","Besok di mana."],e:"Besok = 明日。"},
  {q:"A: Anda bekerja di mana? B: ___",a:"Saya bekerja di kantor.",c:["Saya bekerja di kantor.","Saya bekerja nasi.","Saya bekerja tidur.","Saya bekerja mahal."],e:"bekerja di = 〜で働く。"},
  {q:"A: Anda belajar apa? B: ___",a:"Saya belajar bahasa Indonesia.",c:["Saya belajar bahasa Indonesia.","Saya belajar di mana.","Saya belajar mahal.","Saya belajar jam."],e:"belajar apa = 何を勉強していますか。"},
  {q:"A: Siapa guru Anda? B: ___",a:"Guru saya Pak Budi.",c:["Guru saya Pak Budi.","Guru saya mahal.","Guru saya ke pasar.","Guru saya jam tujuh."],e:"Siapa = 誰。"},
  {q:"A: Di mana buku saya? B: ___",a:"Di atas meja.",c:["Di atas meja.","Jam tujuh.","Besok pagi.","Saya makan."],e:"Di atas meja = 机の上。"},
  {q:"A: Ini punya siapa? B: ___",a:"Ini punya saya.",c:["Ini punya saya.","Ini makan saya.","Ini pergi saya.","Ini tidur saya."],e:"punya siapa = 誰のもの。"},
  {q:"A: Boleh pinjam pensil? B: ___",a:"Boleh, silakan.",c:["Boleh, silakan.","Besok mahal.","Saya dari Jepang.","Di kanan."],e:"pinjam = 借りる。"},
  {q:"A: Apakah Anda mengerti? B: ___",a:"Ya, saya mengerti.",c:["Ya, saya mengerti.","Ya, saya lapar.","Ya, saya mahal.","Ya, saya meja."],e:"mengerti = 理解する。"},
  {q:"A: Bisa ulangi? B: ___",a:"Baik, saya ulangi.",c:["Baik, saya ulangi.","Baik, saya makan.","Baik, saya tidur.","Baik, saya beli."],e:"ulangi = 繰り返す。"},
  {q:"A: Apa pekerjaan Anda? B: ___",a:"Saya perawat.",c:["Saya perawat.","Saya kantor.","Saya mahal.","Saya jam."],e:"pekerjaan = 職業。"},
  {q:"A: Berapa umur Anda? B: ___",a:"Umur saya dua puluh tahun.",c:["Umur saya dua puluh tahun.","Umur saya di rumah.","Umur saya besok.","Umur saya buku."],e:"umur = 年齢。"},
  {q:"A: Berapa orang di kelas? B: ___",a:"Ada dua puluh orang.",c:["Ada dua puluh orang.","Ada jam dua.","Ada mahal.","Ada besok."],e:"berapa orang = 何人。"},
  {q:"A: Apa nomor telepon Anda? B: ___",a:"Nomor telepon saya 0812.",c:["Nomor telepon saya 0812.","Nomor telepon saya nasi.","Nomor telepon saya tidur.","Nomor telepon saya meja."],e:"nomor telepon = 電話番号。"},
  {q:"A: Sampai jumpa. B: ___",a:"Sampai jumpa.",c:["Sampai jumpa.","Terima kasih makan.","Saya dari mana.","Tidak mahal."],e:"Sampai jumpa = また会いましょう。"},
  {q:"A: Selamat pagi. B: ___",a:"Selamat pagi.",c:["Selamat pagi.","Selamat tidur.","Selamat makan.","Selamat buku."],e:"朝の挨拶は Selamat pagi."}
];
window.reading2Questions = [
  {q:"Saya pergi ke pasar pada pagi hari. Saya membeli sayur dan buah. Pertanyaan: Saya pergi ke mana?",a:"Ke pasar",c:["Ke pasar","Ke sekolah","Ke kantor","Ke rumah sakit"],e:"本文：Saya pergi ke pasar = 私は市場へ行きました。"},
  {q:"Ani belajar bahasa Indonesia setiap malam. Dia ingin lulus ujian. Pertanyaan: Ani belajar apa?",a:"Bahasa Indonesia",c:["Bahasa Indonesia","Bahasa Jepang","Matematika","Musik"],e:"本文：belajar bahasa Indonesia = インドネシア語を勉強する。"},
  {q:"Hari ini hari Senin. Besok saya bekerja. Pertanyaan: Besok hari apa?",a:"Selasa",c:["Selasa","Minggu","Jumat","Sabtu"],e:"Senin の次の日は Selasa。"},
  {q:"Budi makan nasi goreng di restoran. Rasanya enak. Pertanyaan: Apa yang dimakan Budi?",a:"Nasi goreng",c:["Nasi goreng","Roti","Soto","Mie"],e:"本文：Budi makan nasi goreng。"},
  {q:"Ibu membeli ikan di pasar. Ikan itu segar. Pertanyaan: Ibu membeli apa?",a:"Ikan",c:["Ikan","Ayam","Sayur","Buah"],e:"membeli ikan = 魚を買う。"},
  {q:"Saya bangun jam enam pagi. Setelah itu saya mandi. Pertanyaan: Saya bangun jam berapa?",a:"Jam enam",c:["Jam enam","Jam tujuh","Jam delapan","Jam sembilan"],e:"本文：bangun jam enam pagi。"},
  {q:"Di kelas ada sepuluh siswa. Mereka belajar bersama. Pertanyaan: Ada berapa siswa?",a:"Sepuluh",c:["Sepuluh","Sembilan","Delapan","Tujuh"],e:"sepuluh = 10。"},
  {q:"Rina tinggal di Bandung. Dia bekerja di rumah sakit. Pertanyaan: Rina tinggal di mana?",a:"Bandung",c:["Bandung","Jakarta","Bali","Surabaya"],e:"tinggal di Bandung = バンドンに住む。"},
  {q:"Saya suka kopi, tetapi adik saya tidak suka kopi. Pertanyaan: Siapa yang tidak suka kopi?",a:"Adik saya",c:["Adik saya","Saya","Ibu","Ayah"],e:"tidak suka kopi = コーヒーが好きではない。"},
  {q:"Mereka bermain bola di taman pada sore hari. Pertanyaan: Mereka bermain di mana?",a:"Di taman",c:["Di taman","Di sekolah","Di kantor","Di dapur"],e:"bermain bola di taman = 公園でボール遊びをする。"},
  {q:"Ayah pergi ke kantor dengan mobil. Kantor ayah jauh. Pertanyaan: Ayah pergi dengan apa?",a:"Mobil",c:["Mobil","Sepeda","Bus","Kereta"],e:"dengan mobil = 車で。"},
  {q:"Saya membaca buku di perpustakaan. Buku itu menarik. Pertanyaan: Saya membaca apa?",a:"Buku",c:["Buku","Koran","Surat","Majalah"],e:"membaca buku = 本を読む。"},
  {q:"Toko itu buka dari jam sembilan sampai jam lima. Pertanyaan: Toko buka jam berapa?",a:"Jam sembilan",c:["Jam sembilan","Jam lima","Jam enam","Jam tujuh"],e:"buka dari jam sembilan = 9時から開く。"},
  {q:"Kami makan siang di kantin. Setelah makan, kami minum teh. Pertanyaan: Kami makan siang di mana?",a:"Di kantin",c:["Di kantin","Di kelas","Di taman","Di kamar"],e:"makan siang di kantin = 食堂で昼食を食べる。"},
  {q:"Siti membeli tiga buku dan dua pensil. Pertanyaan: Berapa buku yang dibeli Siti?",a:"Tiga",c:["Tiga","Dua","Lima","Satu"],e:"tiga buku = 3冊の本。"},
  {q:"Hari Minggu saya tidak bekerja. Saya beristirahat di rumah. Pertanyaan: Apa yang saya lakukan di rumah?",a:"Beristirahat",c:["Beristirahat","Bekerja","Belanja","Bersepeda"],e:"beristirahat = 休む。"},
  {q:"Pagi ini hujan. Saya membawa payung. Pertanyaan: Mengapa saya membawa payung?",a:"Karena hujan",c:["Karena hujan","Karena panas","Karena lapar","Karena sakit"],e:"hujan = 雨。雨なので傘を持つ。"},
  {q:"Adik minum susu sebelum tidur. Pertanyaan: Adik minum apa?",a:"Susu",c:["Susu","Kopi","Teh","Air"],e:"minum susu = 牛乳を飲む。"},
  {q:"Saya pergi ke sekolah naik bus. Bus datang jam tujuh. Pertanyaan: Bus datang jam berapa?",a:"Jam tujuh",c:["Jam tujuh","Jam enam","Jam lima","Jam delapan"],e:"datang jam tujuh = 7時に来る。"},
  {q:"Di meja ada buku, pensil, dan tas. Pertanyaan: Di mana buku itu?",a:"Di meja",c:["Di meja","Di kursi","Di lantai","Di lemari"],e:"Di meja ada buku = 机に本がある。"},
  {q:"Saya mempunyai dua saudara. Kakak saya bekerja, adik saya sekolah. Pertanyaan: Saya mempunyai berapa saudara?",a:"Dua",c:["Dua","Satu","Tiga","Empat"],e:"dua saudara = 2人の兄弟。"},
  {q:"Roti ini murah. Harganya lima ribu rupiah. Pertanyaan: Berapa harga roti?",a:"Lima ribu rupiah",c:["Lima ribu rupiah","Sepuluh ribu rupiah","Dua ribu rupiah","Seribu rupiah"],e:"harganya lima ribu rupiah = 値段は5000ルピア。"},
  {q:"Saya belajar dari jam tujuh sampai jam sembilan malam. Pertanyaan: Saya belajar sampai jam berapa?",a:"Jam sembilan malam",c:["Jam sembilan malam","Jam tujuh pagi","Jam lima sore","Jam enam pagi"],e:"sampai jam sembilan malam = 夜9時まで。"},
  {q:"Dokter bekerja di rumah sakit. Guru bekerja di sekolah. Pertanyaan: Guru bekerja di mana?",a:"Di sekolah",c:["Di sekolah","Di rumah sakit","Di pasar","Di hotel"],e:"Guru bekerja di sekolah = 先生は学校で働く。"},
  {q:"Saya suka apel. Kakak suka jeruk. Ibu suka pisang. Pertanyaan: Siapa yang suka jeruk?",a:"Kakak",c:["Kakak","Saya","Ibu","Ayah"],e:"Kakak suka jeruk = 兄/姉はみかんが好き。"},
  {q:"Malam ini saya menonton televisi dengan keluarga. Pertanyaan: Saya menonton televisi dengan siapa?",a:"Keluarga",c:["Keluarga","Teman","Guru","Dokter"],e:"dengan keluarga = 家族と。"},
  {q:"Pintu kelas tertutup. Guru membuka pintu. Pertanyaan: Apa yang dibuka guru?",a:"Pintu",c:["Pintu","Jendela","Buku","Tas"],e:"membuka pintu = ドアを開ける。"},
  {q:"Saya tidak minum kopi karena sudah malam. Pertanyaan: Mengapa saya tidak minum kopi?",a:"Karena sudah malam",c:["Karena sudah malam","Karena pagi","Karena lapar","Karena murah"],e:"karena sudah malam = もう夜だから。"},
  {q:"Di rumah saya ada ayah, ibu, dan adik. Pertanyaan: Siapa yang ada di rumah?",a:"Ayah, ibu, dan adik",c:["Ayah, ibu, dan adik","Guru dan teman","Dokter dan pasien","Penjual dan pembeli"],e:"本文そのまま。"},
  {q:"Saya menulis surat untuk teman saya. Pertanyaan: Untuk siapa surat itu?",a:"Teman saya",c:["Teman saya","Guru saya","Ibu saya","Adik saya"],e:"untuk teman saya = 友達のために。"},
  {q:"Kami berangkat pagi-pagi supaya tidak terlambat. Pertanyaan: Mengapa kami berangkat pagi-pagi?",a:"Supaya tidak terlambat",c:["Supaya tidak terlambat","Supaya makan","Supaya tidur","Supaya mahal"],e:"supaya tidak terlambat = 遅れないように。"},
  {q:"Cuaca hari ini panas. Saya minum banyak air. Pertanyaan: Bagaimana cuaca hari ini?",a:"Panas",c:["Panas","Dingin","Hujan","Berangin"],e:"cuaca panas = 暑い天気。"},
  {q:"Saya membeli tiket kereta untuk besok. Pertanyaan: Tiket itu untuk kapan?",a:"Besok",c:["Besok","Hari ini","Kemarin","Minggu lalu"],e:"untuk besok = 明日のため。"},
  {q:"Di kamar ada satu tempat tidur dan satu meja. Pertanyaan: Ada berapa tempat tidur?",a:"Satu",c:["Satu","Dua","Tiga","Empat"],e:"satu tempat tidur = ベッド1つ。"},
  {q:"Anak itu menangis karena lapar. Ibunya memberi makanan. Pertanyaan: Mengapa anak itu menangis?",a:"Karena lapar",c:["Karena lapar","Karena senang","Karena tidur","Karena belajar"],e:"menangis karena lapar = お腹が空いて泣く。"},
  {q:"Saya pergi ke toko buku untuk membeli kamus. Pertanyaan: Saya membeli apa?",a:"Kamus",c:["Kamus","Baju","Sepatu","Obat"],e:"membeli kamus = 辞書を買う。"},
  {q:"Setiap hari Jumat kami rapat di kantor. Pertanyaan: Kapan kami rapat?",a:"Setiap hari Jumat",c:["Setiap hari Jumat","Setiap hari Senin","Setiap pagi Minggu","Setiap malam"],e:"Setiap hari Jumat = 毎週金曜日。"},
  {q:"Nenek sedang duduk di kursi. Dia membaca koran. Pertanyaan: Apa yang dibaca nenek?",a:"Koran",c:["Koran","Buku","Surat","Majalah"],e:"membaca koran = 新聞を読む。"},
  {q:"Saya membeli obat karena kepala saya sakit. Pertanyaan: Mengapa saya membeli obat?",a:"Karena kepala saya sakit",c:["Karena kepala saya sakit","Karena saya lapar","Karena saya senang","Karena saya belajar"],e:"kepala saya sakit = 頭が痛い。"},
  {q:"Pagi hari saya sarapan roti dan telur. Pertanyaan: Apa sarapan saya?",a:"Roti dan telur",c:["Roti dan telur","Nasi dan ikan","Kopi dan teh","Sayur dan buah"],e:"sarapan roti dan telur = パンと卵の朝食。"}
];
