questionBank.push(
  q("CONV-A001","会話","★★☆","A: Selamat pagi. B: ___","A：おはようございます。Bの返答を選びます。",["Selamat pagi","Terima kasih","Maaf","Sampai jumpa"],"Selamat pagi","スラマット パギ","Selamat pagi＝おはようございます","あいさつには同じあいさつで返すのが自然です。",{"Terima kasih":"ありがとうです。","Maaf":"すみませんです。","Sampai jumpa":"また会いましょうです。"},["pagi＝朝","selamat＝安全・平安"]),
  q("CONV-A002","会話","★★☆","A: Terima kasih. B: ___","A：ありがとうございます。Bの返答を選びます。",["Sama-sama","Maaf","Selamat malam","Tidak apa-apa"],"Sama-sama","サマサマ","Sama-sama＝どういたしまして","お礼への返答です。",{"Maaf":"すみませんです。","Selamat malam":"こんばんはです。","Tidak apa-apa":"大丈夫です。"},["terima kasih＝ありがとう","sama-sama＝どういたしまして"]),
  q("CONV-A003","会話","★★☆","A: Maaf. B: ___","A：すみません。Bの返答を選びます。",["Tidak apa-apa","Terima kasih","Selamat pagi","Sampai jumpa"],"Tidak apa-apa","ティダッ アパアパ","Tidak apa-apa＝大丈夫です","謝罪への返答として使います。",{"Terima kasih":"ありがとうです。","Selamat pagi":"おはようです。","Sampai jumpa":"また会いましょうです。"},["maaf＝すみません","apa＝何"]),
  q("CONV-A004","会話","★★☆","A: Sampai jumpa. B: ___","A：また会いましょう。Bの返答を選びます。",["Sampai jumpa","Maaf","Terima kasih","Selamat siang"],"Sampai jumpa","サンパイ ジュンパ","Sampai jumpa＝また会いましょう","別れのあいさつには同じ表現で返せます。",{"Maaf":"すみませんです。","Terima kasih":"ありがとうです。","Selamat siang":"こんにちはです。"},["sampai＝〜まで","jumpa＝会う"]),
  q("CONV-A005","会話","★★☆","A: Apa kabar? B: ___","A：元気ですか。Bの返答を選びます。",["Baik","Selamat malam","Maaf","Di rumah"],"Baik","バイク","Baik＝元気です・良いです","Apa kabar? には Baik と返せます。",{"Selamat malam":"こんばんはです。","Maaf":"すみませんです。","Di rumah":"家でです。"},["apa kabar＝元気ですか","baik＝良い"]),

  q("CONV-A006","会話","★★☆","A: Siapa nama Anda? B: ___","A：あなたの名前は何ですか。Bの返答を選びます。",["Nama saya Budi","Saya dari Jepang","Saya di rumah","Saya makan nasi"],"Nama saya Budi","ナマ サヤ ブディ","Nama saya〜＝私の名前は〜です","名前を聞かれているので nama saya を使います。",{"Saya dari Jepang":"出身を答えています。","Saya di rumah":"場所を答えています。","Saya makan nasi":"食べる内容です。"},["nama＝名前","saya＝私"]),
  q("CONV-A007","会話","★★☆","A: Dari mana Anda? B: ___","A：あなたはどこから来ましたか。Bの返答を選びます。",["Saya dari Jepang","Nama saya Ani","Saya suka kopi","Saya tidur"],"Saya dari Jepang","サヤ ダリ ジュパン","Saya dari Jepang＝私は日本から来ました","dari mana は出身・どこからを尋ねます。",{"Nama saya Ani":"名前の答えです。","Saya suka kopi":"好みです。","Saya tidur":"寝ますです。"},["dari＝〜から","mana＝どこ"]),
  q("CONV-A008","会話","★★☆","A: Mau ke mana? B: ___","A：どこへ行きますか。Bの返答を選びます。",["Ke sekolah","Dari Jepang","Nama saya Tono","Terima kasih"],"Ke sekolah","ク スコラ","Ke sekolah＝学校へ","ke mana は行き先を尋ねます。",{"Dari Jepang":"〜からです。","Nama saya Tono":"名前です。","Terima kasih":"ありがとうです。"},["ke＝〜へ","sekolah＝学校"]),
  q("CONV-A009","会話","★★☆","A: Di mana rumah sakit? B: ___","A：病院はどこですか。Bの返答を選びます。",["Di depan bank","Saya dokter","Saya sakit","Terima kasih"],"Di depan bank","ディ ドゥパン バンク","Di depan bank＝銀行の前です","場所を聞かれているので場所で答えます。",{"Saya dokter":"私は医者です。","Saya sakit":"私は病気です。","Terima kasih":"ありがとうです。"},["di depan＝〜の前","bank＝銀行"]),
  q("CONV-A010","会話","★★☆","A: Jam berapa sekarang? B: ___","A：今何時ですか。Bの返答を選びます。",["Jam tujuh","Hari Senin","Bulan Mei","Di sekolah"],"Jam tujuh","ジャム トゥジュ","Jam tujuh＝7時です","jam berapa は時刻を尋ねます。",{"Hari Senin":"月曜日です。","Bulan Mei":"5月です。","Di sekolah":"学校でです。"},["jam＝時","berapa＝いくつ"]),

  q("CONV-A011","会話","★★☆","A: Berapa harganya? B: ___","A：値段はいくらですか。Bの返答を選びます。",["Sepuluh ribu rupiah","Jam sepuluh","Hari Minggu","Di pasar"],"Sepuluh ribu rupiah","スプル リブ ルピア","Sepuluh ribu rupiah＝1万ルピア","harga は値段です。",{"Jam sepuluh":"10時です。","Hari Minggu":"日曜日です。","Di pasar":"市場でです。"},["harga＝値段","rupiah＝ルピア"]),
  q("CONV-A012","会話","★★☆","A: Anda suka kopi? B: ___","A：コーヒーが好きですか。Bの返答を選びます。",["Ya, saya suka kopi","Saya dari Jepang","Jam tujuh","Di rumah"],"Ya, saya suka kopi","ヤ サヤ スカ コピ","Ya, saya suka kopi＝はい、私はコーヒーが好きです","好きか聞かれているので suka で答えます。",{"Saya dari Jepang":"出身です。","Jam tujuh":"時刻です。","Di rumah":"場所です。"},["ya＝はい","suka＝好き"]),
  q("CONV-A013","会話","★★☆","A: Anda sudah makan? B: ___","A：もう食べましたか。Bの返答を選びます。",["Sudah","Di sekolah","Nama saya Ani","Selamat pagi"],"Sudah","スダッ","Sudah＝もう・すでに","sudah で聞かれたら sudah / belum で答えます。",{"Di sekolah":"場所です。","Nama saya Ani":"名前です。","Selamat pagi":"あいさつです。"},["sudah＝もう","belum＝まだ"]),
  q("CONV-A014","会話","★★☆","A: Anda sudah mandi? B: ___","A：もう入浴しましたか。Bの返答を選びます。",["Belum","Ke pasar","Terima kasih","Hari ini"],"Belum","ブルム","Belum＝まだです","まだしていない時は belum です。",{"Ke pasar":"市場へです。","Terima kasih":"ありがとうです。","Hari ini":"今日です。"},["mandi＝入浴する","belum＝まだ"]),
  q("CONV-A015","会話","★★☆","A: Boleh saya masuk? B: ___","A：入ってもいいですか。Bの返答を選びます。",["Silakan","Selamat tidur","Jam dua","Saya makan"],"Silakan","シラカン","Silakan＝どうぞ","許可・すすめる時に使います。",{"Selamat tidur":"おやすみなさいです。","Jam dua":"2時です。","Saya makan":"私は食べます。"},["boleh＝〜してよい","masuk＝入る"]),

  q("CONV-A016","会話","★★☆","A: Tolong buka pintu. B: ___","A：ドアを開けてください。Bの返答を選びます。",["Baik","Selamat malam","Sampai jumpa","Saya dari Jepang"],"Baik","バイク","Baik＝はい・わかりました","依頼への返事として使えます。",{"Selamat malam":"こんばんはです。","Sampai jumpa":"また会いましょうです。","Saya dari Jepang":"私は日本からです。"},["tolong＝〜してください","pintu＝ドア"]),
  q("CONV-A017","会話","★★☆","A: Jangan merokok di sini. B: ___","A：ここでタバコを吸わないでください。Bの返答を選びます。",["Baik","Terima kasih kembali","Selamat pagi","Apa kabar"],"Baik","バイク","Baik＝わかりました","注意・禁止に対する返答として自然です。",{"Terima kasih kembali":"どういたしましてです。","Selamat pagi":"おはようです。","Apa kabar":"元気ですかです。"},["jangan＝〜しないで","merokok＝タバコを吸う"]),
  q("CONV-A018","会話","★★☆","A: Permisi. B: ___","A：失礼します。Bの返答を選びます。",["Ya, silakan","Saya makan","Besok pagi","Dua orang"],"Ya, silakan","ヤ シラカン","Ya, silakan＝はい、どうぞ","permisi は失礼します・すみませんです。",{"Saya makan":"私は食べます。","Besok pagi":"明日の朝です。","Dua orang":"2人です。"},["permisi＝失礼します","silakan＝どうぞ"]),
  q("CONV-A019","会話","★★☆","A: Selamat tidur. B: ___","A：おやすみなさい。Bの返答を選びます。",["Selamat tidur","Selamat siang","Terima kasih","Maaf"],"Selamat tidur","スラマット ティドゥル","Selamat tidur＝おやすみなさい","寝る前のあいさつです。",{"Selamat siang":"こんにちはです。","Terima kasih":"ありがとうです。","Maaf":"すみませんです。"},["tidur＝寝る","malam＝夜"]),
  q("CONV-A020","会話","★★☆","A: Apa ini? B: ___","A：これは何ですか。Bの返答を選びます。",["Ini buku","Saya Budi","Di pasar","Jam tiga"],"Ini buku","イニ ブク","Ini buku＝これは本です","Apa ini? は『これは何ですか』です。",{"Saya Budi":"私はブディです。","Di pasar":"市場でです。","Jam tiga":"3時です。"},["apa＝何","ini＝これ"]),

  q("CONV-A021","会話","★★★","A: Siapa dia? B: ___","A：彼・彼女は誰ですか。Bの返答を選びます。",["Dia guru","Di rumah","Jam lima","Besok"],"Dia guru","ディア グル","Dia guru＝彼・彼女は先生です","siapa は誰ですかです。",{"Di rumah":"家でです。","Jam lima":"5時です。","Besok":"明日です。"},["siapa＝誰","dia＝彼・彼女"]),
  q("CONV-A022","会話","★★☆","A: Kapan Anda pergi? B: ___","A：あなたはいつ行きますか。Bの返答を選びます。",["Besok pagi","Ke sekolah","Dari Jepang","Dua buah"],"Besok pagi","ベソッ パギ","Besok pagi＝明日の朝","kapan はいつを尋ねます。",{"Ke sekolah":"学校へです。","Dari Jepang":"日本からです。","Dua buah":"2個です。"},["kapan＝いつ","besok＝明日"]),
  q("CONV-A023","会話","★★☆","A: Dengan siapa Anda pergi? B: ___","A：あなたは誰と行きますか。Bの返答を選びます。",["Dengan teman","Ke pasar","Jam tujuh","Minggu"],"Dengan teman","ドゥンガン トゥマン","Dengan teman＝友だちと","dengan siapa は誰と、です。",{"Ke pasar":"市場へです。","Jam tujuh":"7時です。","Minggu":"日曜日・週です。"},["dengan＝〜と","teman＝友だち"]),
  q("CONV-A024","会話","★★☆","A: Anda tinggal di mana? B: ___","A：あなたはどこに住んでいますか。Bの返答を選びます。",["Di Tokyo","Dari Tokyo","Ke Tokyo","Jam tujuh"],"Di Tokyo","ディ トウキョウ","Di Tokyo＝東京に","tinggal di mana は住んでいる場所を尋ねます。",{"Dari Tokyo":"東京からです。","Ke Tokyo":"東京へです。","Jam tujuh":"7時です。"},["tinggal＝住む","di＝〜に"]),
  q("CONV-A025","会話","★★☆","A: Berapa orang datang? B: ___","A：何人来ますか。Bの返答を選びます。",["Tiga orang","Tiga ekor","Tiga buah","Tiga lembar"],"Tiga orang","ティガ オラン","Tiga orang＝3人","人を数えるので orang です。",{"Tiga ekor":"3匹です。","Tiga buah":"3個です。","Tiga lembar":"3枚です。"},["berapa orang＝何人","datang＝来る"]),

  q("CONV-A026","会話","★★☆","A: Berapa ekor kucing? B: ___","A：猫は何匹ですか。Bの返答を選びます。",["Dua ekor","Dua orang","Dua lembar","Dua hari"],"Dua ekor","ドゥア エコール","Dua ekor＝2匹","動物を数えるので ekor です。",{"Dua orang":"2人です。","Dua lembar":"2枚です。","Dua hari":"2日です。"},["ekor＝動物用助数詞","kucing＝猫"]),
  q("CONV-A027","会話","★★☆","A: Di mana buku saya? B: ___","A：私の本はどこですか。Bの返答を選びます。",["Di atas meja","Saya guru","Besok pagi","Terima kasih"],"Di atas meja","ディ アタス メジャ","Di atas meja＝机の上です","場所を尋ねているので場所で答えます。",{"Saya guru":"私は先生です。","Besok pagi":"明日の朝です。","Terima kasih":"ありがとうです。"},["di atas＝〜の上","meja＝机"]),
  q("CONV-A028","会話","★★☆","A: Mengapa Anda tidak datang? B: ___","A：なぜ来ないのですか。Bの返答を選びます。",["Karena sakit","Ke sekolah","Tiga orang","Selamat pagi"],"Karena sakit","カレナ サキット","Karena sakit＝病気だからです","mengapa はなぜ、karena は〜だからです。",{"Ke sekolah":"学校へです。","Tiga orang":"3人です。","Selamat pagi":"おはようです。"},["mengapa＝なぜ","karena＝〜だから"]),
  q("CONV-A029","会話","★★★","A: Mana yang benar? B: ___","A：どれが正しいですか。Bの返答を選びます。",["Yang ini","Di rumah","Jam dua","Terima kasih"],"Yang ini","ヤン イニ","Yang ini＝これです","mana はどれ、yang ini はこれです。",{"Di rumah":"家でです。","Jam dua":"2時です。","Terima kasih":"ありがとうです。"},["mana＝どれ","benar＝正しい"]),
  q("CONV-A030","会話","★★☆","A: Sampai besok. B: ___","A：また明日。Bの返答を選びます。",["Sampai besok","Selamat pagi","Maaf","Di sini"],"Sampai besok","サンパイ ベソッ","Sampai besok＝また明日","別れのあいさつとして使います。",{"Selamat pagi":"おはようです。","Maaf":"すみませんです。","Di sini":"ここでです。"},["sampai＝〜まで","besok＝明日"])
);
