questionBank.push(
  q("ME-A001","me動詞","★★★","baca の正しい me-形は？","baca の me形を選びます。",["membaca","menbaca","mengbaca","menybaca"],"membaca","ムンバチャ","membaca＝読む","baca は b で始まる語根なので membaca になります。",{"menbaca":"誤った形です。","mengbaca":"誤った形です。","menybaca":"誤った形です。"},["baca＝読む","buku＝本"]),
  q("ME-A002","me動詞","★★★","tulis の正しい me-形は？","tulis の me形を選びます。",["menulis","memulis","mengulis","menyulis"],"menulis","ムヌリス","menulis＝書く","tulis は t が消えて menulis になります。",{"memulis":"誤った形です。","mengulis":"誤った形です。","menyulis":"誤った形です。"},["tulis＝書く","surat＝手紙"]),
  q("ME-A003","me動詞","★★★","kirim の正しい me-形は？","kirim の me形を選びます。",["mengirim","menirim","memirim","menyirim"],"mengirim","ムンギリム","mengirim＝送る","kirim は k が消えて mengirim になります。",{"menirim":"誤った形です。","memirim":"誤った形です。","menyirim":"誤った形です。"},["kirim＝送る","paket＝荷物"]),
  q("ME-A004","me動詞","★★★","sapu の正しい me-形は？","sapu の me形を選びます。",["menyapu","mensapu","memsapu","mengsapu"],"menyapu","ムニャプ","menyapu＝掃く","sapu は s が消えて menyapu になります。",{"mensapu":"誤った形です。","memsapu":"誤った形です。","mengsapu":"誤った形です。"},["sapu＝ほうき・掃く","lantai＝床"]),
  q("ME-A005","me動詞","★★★","pilih の正しい me-形は？","pilih の me形を選びます。",["memilih","menilih","mengilih","menyilih"],"memilih","ムミリッ","memilih＝選ぶ","pilih は p が消えて memilih になります。",{"menilih":"誤った形です。","mengilih":"誤った形です。","menyilih":"誤った形です。"},["pilih＝選ぶ","jawaban＝答え"]),

  q("ME-A006","me動詞","★★☆","Saya ___ buku.","私は本を読みます。",["membaca","menulis","mencuci","membeli"],"membaca","ムンバチャ","membaca＝読む","buku を読むので membaca が正解です。",{"menulis":"書くです。","mencuci":"洗うです。","membeli":"買うです。"},["buku＝本","membaca buku＝本を読む"]),
  q("ME-A007","me動詞","★★☆","Ibu ___ sayur.","母は野菜を料理します。",["memasak","membaca","menyapu","mengirim"],"memasak","ムマサック","memasak＝料理する","sayur を料理するので memasak です。",{"membaca":"読むです。","menyapu":"掃くです。","mengirim":"送るです。"},["sayur＝野菜","dapur＝台所"]),
  q("ME-A008","me動詞","★★☆","Dia ___ surat.","彼・彼女は手紙を書きます。",["menulis","membaca","mencuci","membeli"],"menulis","ムヌリス","menulis＝書く","surat を書くので menulis が正解です。",{"membaca":"読むです。","mencuci":"洗うです。","membeli":"買うです。"},["surat＝手紙","pensil＝鉛筆"]),
  q("ME-A009","me動詞","★★☆","Kami ___ pakaian.","私たちは服を洗います。",["mencuci","membeli","membaca","menjual"],"mencuci","ムンチュチ","mencuci＝洗う","pakaian は服なので mencuci pakaian です。",{"membeli":"買うです。","membaca":"読むです。","menjual":"売るです。"},["pakaian＝服","air＝水"]),
  q("ME-A010","me動詞","★★☆","Ayah ___ mobil.","父は車を運転します。",["mengendarai","membaca","menulis","menyapu"],"mengendarai","ムングンダライ","mengendarai＝運転する","mobil を運転するので mengendarai が正解です。",{"membaca":"読むです。","menulis":"書くです。","menyapu":"掃くです。"},["mobil＝車","motor＝バイク"]),

  q("ME-A011","me動詞","★★☆","membeli の意味は？","membeli の意味を選びます。",["買う","売る","読む","書く"],"買う","ムンブリ","membeli＝買う","買い物でよく使う動詞です。",{"売る":"menjual です。","読む":"membaca です。","書く":"menulis です。"},["beli＝買う","uang＝お金"]),
  q("ME-A012","me動詞","★★☆","menjual の意味は？","menjual の意味を選びます。",["売る","買う","洗う","送る"],"売る","ムンジュアル","menjual＝売る","jual は売る、menjual は売るという動作です。",{"買う":"membeli です。","洗う":"mencuci です。","送る":"mengirim です。"},["jual＝売る","pasar＝市場"]),
  q("ME-A013","me動詞","★★☆","mencari の意味は？","mencari の意味を選びます。",["探す","料理する","読む","歩く"],"探す","ムンチャリ","mencari＝探す","物や人を探す時に使います。",{"料理する":"memasak です。","読む":"membaca です。","歩く":"berjalan です。"},["cari＝探す","mencari alamat＝住所を探す"]),
  q("ME-A014","me動詞","★★☆","memakai の意味は？","memakai の意味を選びます。",["使う・着る","買う","聞く","開ける"],"使う・着る","ムマカイ","memakai＝使う・着る","服を着る、道具を使うの両方で使えます。",{"買う":"membeli です。","聞く":"mendengar です。","開ける":"membuka です。"},["pakaian＝服","memakai baju＝服を着る"]),
  q("ME-A015","me動詞","★★☆","mendengar の意味は？","mendengar の意味を選びます。",["聞く","見る","読む","話す"],"聞く","ムンドゥンガル","mendengar＝聞く","音や話を聞く時に使います。",{"見る":"melihat です。","読む":"membaca です。","話す":"berbicara です。"},["dengar＝聞く","suara＝声・音"]),

  q("ME-A016","me動詞","★★★","lihat の正しい me-形は？","lihat の me形を選びます。",["melihat","menlihat","memlihat","menglihat"],"melihat","ムリハット","melihat＝見る","lihat は melihat になります。",{"menlihat":"誤った形です。","memlihat":"誤った形です。","menglihat":"誤った形です。"},["lihat＝見る","mata＝目"]),
  q("ME-A017","me動詞","★★★","dengar の正しい me-形は？","dengar の me形を選びます。",["mendengar","memdengar","mengdengar","menydengar"],"mendengar","ムンドゥンガル","mendengar＝聞く","dengar は mendengar になります。",{"memdengar":"誤った形です。","mengdengar":"誤った形です。","menydengar":"誤った形です。"},["dengar＝聞く","suara＝音"]),
  q("ME-A018","me動詞","★★★","buka の正しい me-形は？","buka の me形を選びます。",["membuka","menbuka","mengbuka","menybuka"],"membuka","ムンブカ","membuka＝開ける","buka は b で始まるので membuka です。",{"menbuka":"誤った形です。","mengbuka":"誤った形です。","menybuka":"誤った形です。"},["buka＝開ける","pintu＝ドア"]),
  q("ME-A019","me動詞","★★★","cuci の正しい me-形は？","cuci の me形を選びます。",["mencuci","memcuci","mengcuci","menycuci"],"mencuci","ムンチュチ","mencuci＝洗う","cuci は mencuci になります。",{"memcuci":"誤った形です。","mengcuci":"誤った形です。","menycuci":"誤った形です。"},["cuci＝洗う","pakaian＝服"]),
  q("ME-A020","me動詞","★★★","ambil の正しい me-形は？","ambil の me形を選びます。",["mengambil","menambil","memambil","menyambil"],"mengambil","ムンガンビル","mengambil＝取る","母音で始まる語根は meng- になることが多いです。",{"menambil":"誤った形です。","memambil":"誤った形です。","menyambil":"誤った形です。"},["ambil＝取る","uang＝お金"]),

  q("ME-A021","me動詞","★★☆","Dia ___ uang di meja.","彼・彼女は机の上のお金を取ります。",["mengambil","membaca","menulis","menyapu"],"mengambil","ムンガンビル","mengambil＝取る","uang を取るので mengambil です。",{"membaca":"読むです。","menulis":"書くです。","menyapu":"掃くです。"},["uang＝お金","meja＝机"]),
  q("ME-A022","me動詞","★★☆","Saya ___ pintu.","私はドアを開けます。",["membuka","menutup","mencari","mencuci"],"membuka","ムンブカ","membuka＝開ける","pintu を開けるので membuka です。",{"menutup":"閉めるです。","mencari":"探すです。","mencuci":"洗うです。"},["pintu＝ドア","buka＝開ける"]),
  q("ME-A023","me動詞","★★☆","Ibu ___ pasar.","母は市場を探しています。",["mencari","memasak","membeli","membaca"],"mencari","ムンチャリ","mencari＝探す","pasar を探しているので mencari です。",{"memasak":"料理するです。","membeli":"買うです。","membaca":"読むです。"},["pasar＝市場","cari＝探す"]),
  q("ME-A024","me動詞","★★☆","Saya ___ baju baru.","私は新しい服を買います。",["membeli","menjual","mencuci","menulis"],"membeli","ムンブリ","membeli＝買う","baju baru を買うので membeli です。",{"menjual":"売るです。","mencuci":"洗うです。","menulis":"書くです。"},["baju＝服","baru＝新しい"]),
  q("ME-A025","me動詞","★★☆","Dia ___ makanan di pasar.","彼・彼女は市場で食べ物を売ります。",["menjual","membeli","mencuci","membaca"],"menjual","ムンジュアル","menjual＝売る","makanan を売るので menjual です。",{"membeli":"買うです。","mencuci":"洗うです。","membaca":"読むです。"},["makanan＝食べ物","pasar＝市場"]),

  q("ME-A026","me動詞","★★☆","Saya ___ suara burung.","私は鳥の声を聞きます。",["mendengar","melihat","membaca","menulis"],"mendengar","ムンドゥンガル","mendengar＝聞く","suara は音・声なので mendengar です。",{"melihat":"見るです。","membaca":"読むです。","menulis":"書くです。"},["suara＝声・音","burung＝鳥"]),
  q("ME-A027","me動詞","★★☆","Kami ___ rumah besar.","私たちは大きな家を見ます。",["melihat","mendengar","mencuci","mengirim"],"melihat","ムリハット","melihat＝見る","rumah を見るので melihat です。",{"mendengar":"聞くです。","mencuci":"洗うです。","mengirim":"送るです。"},["rumah＝家","besar＝大きい"]),
  q("ME-A028","me動詞","★★☆","Saya ___ paket ke Jakarta.","私は荷物をジャカルタへ送ります。",["mengirim","membeli","menjual","mencuci"],"mengirim","ムンギリム","mengirim＝送る","paket を送るので mengirim です。",{"membeli":"買うです。","menjual":"売るです。","mencuci":"洗うです。"},["paket＝荷物","ke＝〜へ"]),
  q("ME-A029","me動詞","★★☆","Dia ___ lantai setiap pagi.","彼・彼女は毎朝床を掃きます。",["menyapu","membuka","mencari","membeli"],"menyapu","ムニャプ","menyapu＝掃く","lantai を掃くので menyapu です。",{"membuka":"開けるです。","mencari":"探すです。","membeli":"買うです。"},["lantai＝床","setiap pagi＝毎朝"]),
  q("ME-A030","me動詞","★★☆","Saya ___ jawaban yang benar.","私は正しい答えを選びます。",["memilih","membaca","mengirim","mencuci"],"memilih","ムミリッ","memilih＝選ぶ","jawaban を選ぶので memilih です。",{"membaca":"読むです。","mengirim":"送るです。","mencuci":"洗うです。"},["jawaban＝答え","benar＝正しい"])
);
