questionBank.push(
  q("ME-B001","me動詞応用","★★★","buat の正しい me-形は？","buat の me形を選びます。",["membuat","menbuat","mengbuat","menybuat"],"membuat","ムンブアット","membuat＝作る","buat は b で始まるので membuat になります。",{"menbuat":"誤りです。","mengbuat":"誤りです。","menybuat":"誤りです。"},["buat＝作る","makanan＝食べ物"]),
  q("ME-B002","me動詞応用","★★★","bayar の正しい me-形は？","bayar の me形を選びます。",["membayar","menbayar","mengbayar","menybayar"],"membayar","ムンバヤール","membayar＝支払う","bayar は b で始まるので membayar です。",{"menbayar":"誤りです。","mengbayar":"誤りです。","menybayar":"誤りです。"},["bayar＝支払う","uang＝お金"]),
  q("ME-B003","me動詞応用","★★★","panggil の正しい me-形は？","panggil の me形を選びます。",["memanggil","menanggil","menganggil","menyanggil"],"memanggil","ムマンギル","memanggil＝呼ぶ","p で始まる語根は p が消えて mem- になることがあります。",{"menanggil":"誤りです。","menganggil":"誤りです。","menyanggil":"誤りです。"},["panggil＝呼ぶ","nama＝名前"]),
  q("ME-B004","me動詞応用","★★★","pakai の正しい me-形は？","pakai の me形を選びます。",["memakai","menakai","mengakai","menyakai"],"memakai","ムマカイ","memakai＝使う・着る","pakai は p が消えて memakai になります。",{"menakai":"誤りです。","mengakai":"誤りです。","menyakai":"誤りです。"},["pakai＝使う","baju＝服"]),
  q("ME-B005","me動詞応用","★★★","pinjam の正しい me-形は？","pinjam の me形を選びます。",["meminjam","meninjam","menginjam","menyinjam"],"meminjam","ムミンジャム","meminjam＝借りる","pinjam は p が消えて meminjam になります。",{"meninjam":"誤りです。","menginjam":"誤りです。","menyinjam":"誤りです。"},["pinjam＝借りる","buku＝本"]),

  q("ME-B006","me動詞応用","★★★","tutup の正しい me-形は？","tutup の me形を選びます。",["menutup","memutup","mengutup","menyutup"],"menutup","ムヌトゥップ","menutup＝閉める","tutup は t が消えて menutup になります。",{"memutup":"誤りです。","mengutup":"誤りです。","menyutup":"誤りです。"},["tutup＝閉める","pintu＝ドア"]),
  q("ME-B007","me動詞応用","★★★","tarik の正しい me-形は？","tarik の me形を選びます。",["menarik","memarik","mengarik","menyarik"],"menarik","ムナリック","menarik＝引く","tarik は t が消えて menarik になります。",{"memarik":"誤りです。","mengarik":"誤りです。","menyarik":"誤りです。"},["tarik＝引く","dorong＝押す"]),
  q("ME-B008","me動詞応用","★★★","tolong の正しい me-形は？","tolong の me形を選びます。",["menolong","memolong","mengolong","menyolong"],"menolong","ムノロン","menolong＝助ける","tolong は t が消えて menolong になります。",{"memolong":"誤りです。","mengolong":"誤りです。","menyolong":"誤りです。"},["tolong＝助ける・お願い","orang＝人"]),
  q("ME-B009","me動詞応用","★★★","tanya の正しい me-形は？","tanya の me形を選びます。",["menanya","memanya","menganya","menyanya"],"menanya","ムナニャ","menanya＝質問する","tanya は t が消えて menanya になります。",{"memanya":"誤りです。","menganya":"誤りです。","menyanya":"誤りです。"},["tanya＝質問する","jawab＝答える"]),
  q("ME-B010","me動詞応用","★★★","tunggu の正しい me-形は？","tunggu の me形を選びます。",["menunggu","memunggu","mengunggu","menyunggu"],"menunggu","ムヌング","menunggu＝待つ","tunggu は t が消えて menunggu になります。",{"memunggu":"誤りです。","mengunggu":"誤りです。","menyunggu":"誤りです。"},["tunggu＝待つ","sebentar＝少し"]),

  q("ME-B011","me動詞応用","★★★","simpan の正しい me-形は？","simpan の me形を選びます。",["menyimpan","mensimpan","memsimpan","mengsimpan"],"menyimpan","ムニンパン","menyimpan＝保管する","s で始まる語根は s が消えて meny- になることがあります。",{"mensimpan":"誤りです。","memsimpan":"誤りです。","mengsimpan":"誤りです。"},["simpan＝保管する","uang＝お金"]),
  q("ME-B012","me動詞応用","★★★","sewa の正しい me-形は？","sewa の me形を選びます。",["menyewa","mensewa","memsewa","mengsewa"],"menyewa","ムニェワ","menyewa＝借りる・賃借する","sewa は s が消えて menyewa になります。",{"mensewa":"誤りです。","memsewa":"誤りです。","mengsewa":"誤りです。"},["sewa＝借りる","rumah＝家"]),
  q("ME-B013","me動詞応用","★★★","sambut の正しい me-形は？","sambut の me形を選びます。",["menyambut","mensambut","memsambut","mengsambut"],"menyambut","ムニャンブット","menyambut＝迎える","sambut は s が消えて menyambut です。",{"mensambut":"誤りです。","memsambut":"誤りです。","mengsambut":"誤りです。"},["sambut＝迎える","tamu＝客"]),
  q("ME-B014","me動詞応用","★★★","suruh の正しい me-形は？","suruh の me形を選びます。",["menyuruh","mensuruh","memsuruh","mengsuruh"],"menyuruh","ムニュルー","menyuruh＝命じる・頼む","suruh は s が消えて menyuruh です。",{"mensuruh":"誤りです。","memsuruh":"誤りです。","mengsuruh":"誤りです。"},["suruh＝命じる","tolong＝助ける"]),
  q("ME-B015","me動詞応用","★★★","sayang の正しい me-形は？","sayang の me形を選びます。",["menyayangi","mensayangi","memsayangi","mengsayangi"],"menyayangi","ムニャヤギ","menyayangi＝愛する・大切にする","s が消えて menyayangi になります。",{"mensayangi":"誤りです。","memsayangi":"誤りです。","mengsayangi":"誤りです。"},["sayang＝愛情","keluarga＝家族"]),

  q("ME-B016","me動詞応用","★★★","gambar の正しい me-形は？","gambar の me形を選びます。",["menggambar","mengambar","menambar","memgambar"],"menggambar","ムンガンバル","menggambar＝描く","gambar は meng- がついて menggambar になります。",{"mengambar":"誤りです。","menambar":"誤りです。","memgambar":"誤りです。"},["gambar＝絵","pensil＝鉛筆"]),
  q("ME-B017","me動詞応用","★★★","gunting の正しい me-形は？","gunting の me形を選びます。",["menggunting","mengunting","menunting","memgunting"],"menggunting","ムングンティン","menggunting＝切る","gunting は menggunting になります。",{"mengunting":"誤りです。","menunting":"誤りです。","memgunting":"誤りです。"},["gunting＝はさみ・切る","kertas＝紙"]),
  q("ME-B018","me動詞応用","★★★","ganggu の正しい me-形は？","ganggu の me形を選びます。",["mengganggu","menganggu","menanggu","memganggu"],"mengganggu","ムンガング","mengganggu＝邪魔する","ganggu は mengganggu になります。",{"menganggu":"誤りです。","menanggu":"誤りです。","memganggu":"誤りです。"},["ganggu＝邪魔する","jangan＝〜しないで"]),
  q("ME-B019","me動詞応用","★★★","gosok の正しい me-形は？","gosok の me形を選びます。",["menggosok","mengosok","menosok","memgosok"],"menggosok","ムンゴソック","menggosok＝こする・磨く","gosok は menggosok です。",{"mengosok":"誤りです。","menosok":"誤りです。","memgosok":"誤りです。"},["gosok gigi＝歯を磨く","gigi＝歯"]),
  q("ME-B020","me動詞応用","★★★","ganti の正しい me-形は？","ganti の me形を選びます。",["mengganti","menganti","menanti","memganti"],"mengganti","ムンガンティ","mengganti＝替える・交換する","ganti は mengganti になります。",{"menganti":"誤りです。","menanti":"待つという別語です。","memganti":"誤りです。"},["ganti＝替える","baju＝服"]),

  q("ME-B021","me動詞応用","★★☆","Saya ___ pintu setelah masuk.","私は入った後、ドアを閉めます。",["menutup","membuka","mencari","membeli"],"menutup","ムヌトゥップ","menutup＝閉める","pintu を閉めるので menutup です。",{"membuka":"開けるです。","mencari":"探すです。","membeli":"買うです。"},["pintu＝ドア","setelah＝〜の後"]),
  q("ME-B022","me動詞応用","★★☆","Ibu ___ uang di lemari.","母はお金を戸棚に保管します。",["menyimpan","membaca","menjual","mencuci"],"menyimpan","ムニンパン","menyimpan＝保管する","uang を保管するので menyimpan です。",{"membaca":"読むです。","menjual":"売るです。","mencuci":"洗うです。"},["uang＝お金","lemari＝戸棚"]),
  q("ME-B023","me動詞応用","★★☆","Dia ___ gambar dengan pensil.","彼・彼女は鉛筆で絵を描きます。",["menggambar","membeli","menulis","mencuci"],"menggambar","ムンガンバル","menggambar＝描く","gambar を描くので menggambar です。",{"membeli":"買うです。","menulis":"書くです。","mencuci":"洗うです。"},["gambar＝絵","pensil＝鉛筆"]),
  q("ME-B024","me動詞応用","★★☆","Saya ___ gigi setiap pagi.","私は毎朝歯を磨きます。",["menggosok","membaca","mengirim","mencari"],"menggosok","ムンゴソック","menggosok gigi＝歯を磨く","gigi は歯です。",{"membaca":"読むです。","mengirim":"送るです。","mencari":"探すです。"},["gigi＝歯","setiap pagi＝毎朝"]),
  q("ME-B025","me動詞応用","★★☆","Ayah ___ baju sebelum bekerja.","父は働く前に服を替えます。",["mengganti","membaca","menyapu","menjual"],"mengganti","ムンガンティ","mengganti＝替える","baju を替えるので mengganti です。",{"membaca":"読むです。","menyapu":"掃くです。","menjual":"売るです。"},["baju＝服","sebelum＝〜の前に"]),

  q("ME-B026","me動詞応用","★★☆","Guru ___ murid di kelas.","先生は教室で生徒を教えます。",["mengajar","membeli","menjual","menyapu"],"mengajar","ムンガジャル","mengajar＝教える","murid を教えるので mengajar です。",{"membeli":"買うです。","menjual":"売るです。","menyapu":"掃くです。"},["guru＝先生","murid＝生徒"]),
  q("ME-B027","me動詞応用","★★☆","Saya ___ uang sebelum membeli makanan.","私は食べ物を買う前にお金を数えます。",["menghitung","membuka","mencuci","menjual"],"menghitung","ムンヒトゥン","menghitung＝数える","uang を数えるので menghitung です。",{"membuka":"開けるです。","mencuci":"洗うです。","menjual":"売るです。"},["hitung＝数える","uang＝お金"]),
  q("ME-B028","me動詞応用","★★☆","Dia ___ tamu di depan rumah.","彼・彼女は家の前で客を迎えます。",["menyambut","mencuci","membaca","mencari"],"menyambut","ムニャンブット","menyambut＝迎える","tamu を迎えるので menyambut です。",{"mencuci":"洗うです。","membaca":"読むです。","mencari":"探すです。"},["tamu＝客","depan＝前"]),
  q("ME-B029","me動詞応用","★★☆","Saya ___ dokter karena sakit.","私は病気なので医者を呼びます。",["memanggil","membeli","menjual","mencuci"],"memanggil","ムマンギル","memanggil＝呼ぶ","dokter を呼ぶので memanggil です。",{"membeli":"買うです。","menjual":"売るです。","mencuci":"洗うです。"},["dokter＝医者","sakit＝病気"]),
  q("ME-B030","me動詞応用","★★☆","Ibu ___ nasi untuk keluarga.","母は家族のためにご飯を作ります。",["membuat","menulis","mengirim","menyapu"],"membuat","ムンブアット","membuat＝作る","nasi を作るので membuat です。",{"menulis":"書くです。","mengirim":"送るです。","menyapu":"掃くです。"},["nasi＝ご飯","keluarga＝家族"]),

  q("ME-B031","me動詞応用","★★☆","Saya ___ buku dari teman.","私は友だちから本を借ります。",["meminjam","membeli","menjual","menutup"],"meminjam","ムミンジャム","meminjam＝借りる","buku を借りるので meminjam です。",{"membeli":"買うです。","menjual":"売るです。","menutup":"閉めるです。"},["pinjam＝借りる","teman＝友だち"]),
  q("ME-B032","me動詞応用","★★☆","Dia ___ uang di kasir.","彼・彼女はレジでお金を支払います。",["membayar","mencari","mencuci","menulis"],"membayar","ムンバヤール","membayar＝支払う","お金を支払うので membayar です。",{"mencari":"探すです。","mencuci":"洗うです。","menulis":"書くです。"},["kasir＝レジ","uang＝お金"]),
  q("ME-B033","me動詞応用","★★☆","Kami ___ rumah kecil.","私たちは小さな家を借ります。",["menyewa","membaca","menyapu","mengirim"],"menyewa","ムニェワ","menyewa＝借りる・賃借する","rumah を借りるので menyewa です。",{"membaca":"読むです。","menyapu":"掃くです。","mengirim":"送るです。"},["rumah＝家","kecil＝小さい"]),
  q("ME-B034","me動詞応用","★★☆","Saya ___ kertas dengan gunting.","私ははさみで紙を切ります。",["menggunting","menulis","membeli","menutup"],"menggunting","ムングンティン","menggunting＝切る","kertas をはさみで切るので menggunting です。",{"menulis":"書くです。","membeli":"買うです。","menutup":"閉めるです。"},["gunting＝はさみ","kertas＝紙"]),
  q("ME-B035","me動詞応用","★★☆","Jangan ___ orang lain.","他の人を邪魔しないでください。",["mengganggu","membaca","membeli","menulis"],"mengganggu","ムンガング","mengganggu＝邪魔する","jangan と一緒に禁止表現になります。",{"membaca":"読むです。","membeli":"買うです。","menulis":"書くです。"},["jangan＝〜しないで","orang lain＝他の人"]),

  q("ME-B036","me動詞応用","★★☆","memilih の意味は？","memilih の意味を選びます。",["選ぶ","借りる","支払う","閉める"],"選ぶ","ムミリッ","memilih＝選ぶ","pilih が語根です。",{"借りる":"meminjam です。","支払う":"membayar です。","閉める":"menutup です。"},["pilih＝選ぶ","jawaban＝答え"]),
  q("ME-B037","me動詞応用","★★☆","menunggu の意味は？","menunggu の意味を選びます。",["待つ","助ける","切る","聞く"],"待つ","ムヌング","menunggu＝待つ","tunggu が語根です。",{"助ける":"menolong です。","切る":"menggunting です。","聞く":"mendengar です。"},["tunggu＝待つ","sebentar＝少し"]),
  q("ME-B038","me動詞応用","★★☆","menolong の意味は？","menolong の意味を選びます。",["助ける","探す","洗う","売る"],"助ける","ムノロン","menolong＝助ける","人を助ける時に使います。",{"探す":"mencari です。","洗う":"mencuci です。","売る":"menjual です。"},["tolong＝助ける・お願い","orang＝人"]),
  q("ME-B039","me動詞応用","★★☆","mengajar の意味は？","mengajar の意味を選びます。",["教える","学ぶ","遊ぶ","歩く"],"教える","ムンガジャル","mengajar＝教える","belajar は勉強する、mengajar は教えるです。",{"学ぶ":"belajar です。","遊ぶ":"bermain です。","歩く":"berjalan です。"},["ajar＝教える","guru＝先生"]),
  q("ME-B040","me動詞応用","★★☆","menghitung の意味は？","menghitung の意味を選びます。",["数える","開ける","閉める","呼ぶ"],"数える","ムンヒトゥン","menghitung＝数える","数字・お金を数える時に使います。",{"開ける":"membuka です。","閉める":"menutup です。","呼ぶ":"memanggil です。"},["hitung＝数える","angka＝数字"])
);
