questionBank.push(
  q("READ-A001","読解","★★★","Ibu minum air karena haus.","母はなぜ水を飲みますか？",["お腹が空いたから","喉が渇いたから","眠いから","忙しいから"],"喉が渇いたから","イブ ミヌム アイル カレナ ハウス","haus＝喉が渇いた","karena は理由を表します。",{"お腹が空いたから":"lapar です。","眠いから":"mengantuk です。","忙しいから":"sibuk です。"},["air＝水","minum＝飲む","karena＝〜だから"]),
  q("READ-A002","読解","★★★","Ani pergi ke pasar untuk membeli sayur.","アニは何を買うために市場へ行きますか？",["果物","野菜","本","薬"],"野菜","アニ プルギ ク パサール ウントゥック ムンブリ サユール","sayur＝野菜","membeli sayur は『野菜を買う』です。",{"果物":"buah です。","本":"buku です。","薬":"obat です。"},["pasar＝市場","membeli＝買う"]),
  q("READ-A003","読解","★★★","Budi belajar bahasa Indonesia setiap malam.","ブディはいつインドネシア語を勉強しますか？",["毎朝","毎晩","毎週","毎月"],"毎晩","ブディ ブラジャール バハサ インドネシア スティアップ マラム","setiap malam＝毎晩","setiap は『毎〜』、malam は夜です。",{"毎朝":"setiap pagi です。","毎週":"setiap minggu です。","毎月":"setiap bulan です。"},["belajar＝勉強する","malam＝夜"]),
  q("READ-A004","読解","★★☆","Rina tidak suka kopi, tetapi suka teh.","リナが好きな飲み物は何ですか？",["コーヒー","お茶","水","牛乳"],"お茶","リナ ティダッ スカ コピ トゥタピ スカ テー","teh＝お茶","tidak suka kopi なのでコーヒーは好きではありません。tetapi suka teh＝しかしお茶は好きです。",{"コーヒー":"kopi です。","水":"air です。","牛乳":"susu です。"},["tetapi＝しかし","suka＝好き"]),
  q("READ-A005","読解","★★☆","Ayah bekerja di rumah sakit.","父はどこで働いていますか？",["学校","病院","市場","駅"],"病院","アヤ ブクルジャ ディ ルマ サキット","rumah sakit＝病院","di rumah sakit は『病院で』です。",{"学校":"sekolah です。","市場":"pasar です。","駅":"stasiun です。"},["ayah＝父","bekerja＝働く"]),

  q("READ-A006","読解","★★★","Saya belum mandi karena air dingin.","私はなぜまだ入浴していませんか？",["水が冷たいから","眠いから","忙しいから","お腹が空いたから"],"水が冷たいから","サヤ ブルム マンディ カレナ アイル ディンギン","air dingin＝冷たい水","karena は理由を表します。",{"眠いから":"mengantuk です。","忙しいから":"sibuk です。","お腹が空いたから":"lapar です。"},["belum＝まだ〜ない","mandi＝入浴する"]),
  q("READ-A007","読解","★★★","Tono pergi ke apotik untuk membeli obat.","トノは何を買うために薬局へ行きますか？",["薬","本","野菜","服"],"薬","トノ プルギ ク アポティック ウントゥック ムンブリ オバット","obat＝薬","membeli obat は『薬を買う』です。",{"本":"buku です。","野菜":"sayur です。","服":"pakaian です。"},["apotik＝薬局","untuk＝〜のために"]),
  q("READ-A008","読解","★★★","Saya tidak pergi karena hujan.","私はなぜ行きませんか？",["雨だから","暑いから","眠いから","忙しいから"],"雨だから","サヤ ティダッ プルギ カレナ フジャン","hujan＝雨","karena hujan は『雨だから』です。",{"暑いから":"panas です。","眠いから":"mengantuk です。","忙しいから":"sibuk です。"},["tidak pergi＝行かない","karena＝〜だから"]),
  q("READ-A009","読解","★★☆","Adik makan nasi goreng di rumah.","弟・妹はどこでナシゴレンを食べますか？",["家","学校","市場","病院"],"家","アディッ マカン ナシ ゴレン ディ ルマ","di rumah＝家で","場所を表す di に注目します。",{"学校":"sekolah です。","市場":"pasar です。","病院":"rumah sakit です。"},["adik＝弟・妹","nasi goreng＝ナシゴレン"]),
  q("READ-A010","読解","★★☆","Kakak membeli buku di toko.","兄・姉はどこで本を買いますか？",["店","学校","薬局","銀行"],"店","カカッ ムンブリ ブク ディ トコ","toko＝店","di toko は『店で』です。",{"学校":"sekolah です。","薬局":"apotik です。","銀行":"bank です。"},["kakak＝兄・姉","membeli＝買う"]),

  q("READ-A011","読解","★★☆","Mereka bermain sepak bola di lapangan.","彼らはどこでサッカーをしますか？",["運動場","教室","病院","台所"],"運動場","ムレカ ブルマイン スパッ ボラ ディ ラパンガン","lapangan＝運動場","di lapangan は『運動場で』です。",{"教室":"kelas です。","病院":"rumah sakit です。","台所":"dapur です。"},["bermain＝遊ぶ・プレーする","sepak bola＝サッカー"]),
  q("READ-A012","読解","★★☆","Nenek tidur karena capai.","祖母はなぜ寝ますか？",["疲れたから","空腹だから","寒いから","暑いから"],"疲れたから","ネネッ ティドゥル カレナ チャパイ","capai＝疲れた","理由を表す karena に注目します。",{"空腹だから":"lapar です。","寒いから":"dingin です。","暑いから":"panas です。"},["nenek＝祖母","tidur＝寝る"]),
  q("READ-A013","読解","★★★","Pagi ini saya belajar di perpustakaan.","私は今朝どこで勉強しますか？",["図書館","学校","市場","家"],"図書館","パギ イニ サヤ ブラジャール ディ プルプスタカアン","perpustakaan＝図書館","di perpustakaan は『図書館で』です。",{"学校":"sekolah です。","市場":"pasar です。","家":"rumah です。"},["pagi ini＝今朝","belajar＝勉強する"]),
  q("READ-A014","読解","★★☆","Saya pergi ke sekolah dengan bus.","私は何で学校へ行きますか？",["バス","車","自転車","歩いて"],"バス","サヤ プルギ ク スコラ ドゥンガン ブス","dengan bus＝バスで","dengan は手段にも使えます。",{"車":"mobil です。","自転車":"sepeda です。","歩いて":"berjalan です。"},["dengan＝〜で・〜と","bus＝バス"]),
  q("READ-A015","読解","★★☆","Dia membeli baju baru kemarin.","彼・彼女はいつ新しい服を買いましたか？",["昨日","今日","明日","来週"],"昨日","ディア ムンブリ バジュ バル クマリン","kemarin＝昨日","時間表現に注目します。",{"今日":"hari ini です。","明日":"besok です。","来週":"minggu depan です。"},["baju＝服","baru＝新しい"]),

  q("READ-A016","読解","★★★","Kami makan siang di kantin.","私たちはどこで昼食を食べますか？",["食堂","教室","病院","駅"],"食堂","カミ マカン シアン ディ カンティン","kantin＝食堂","di kantin は『食堂で』です。",{"教室":"kelas です。","病院":"rumah sakit です。","駅":"stasiun です。"},["makan siang＝昼食を食べる","kantin＝食堂"]),
  q("READ-A017","読解","★★☆","Adik menangis karena sakit.","弟・妹はなぜ泣いていますか？",["病気・痛いから","嬉しいから","眠いから","忙しいから"],"病気・痛いから","アディッ ムナンギス カレナ サキット","sakit＝病気・痛い","karena sakit は『病気・痛いから』です。",{"嬉しいから":"senang です。","眠いから":"mengantuk です。","忙しいから":"sibuk です。"},["menangis＝泣く","sakit＝痛い・病気"]),
  q("READ-A018","読解","★★☆","Ibu memasak di dapur setiap pagi.","母はいつ台所で料理しますか？",["毎朝","毎晩","毎週","毎月"],"毎朝","イブ ムマサック ディ ダプル スティアップ パギ","setiap pagi＝毎朝","setiap は『毎〜』です。",{"毎晩":"setiap malam です。","毎週":"setiap minggu です。","毎月":"setiap bulan です。"},["dapur＝台所","memasak＝料理する"]),
  q("READ-A019","読解","★★★","Saya belum makan pagi.","私は何をまだしていませんか？",["朝食を食べる","学校へ行く","本を読む","服を洗う"],"朝食を食べる","サヤ ブルム マカン パギ","belum＝まだ〜ない","makan pagi は朝食を食べるです。",{"学校へ行く":"pergi ke sekolah です。","本を読む":"membaca buku です。","服を洗う":"mencuci pakaian です。"},["belum＝まだ〜ない","makan pagi＝朝食"]),
  q("READ-A020","読解","★★☆","Dia suka membaca buku cerita.","彼・彼女は何を読むのが好きですか？",["物語の本","新聞","手紙","教科書"],"物語の本","ディア スカ ムンバチャ ブク チュリタ","buku cerita＝物語の本","suka membaca は『読むのが好き』です。",{"新聞":"koran です。","手紙":"surat です。","教科書":"buku pelajaran です。"},["cerita＝物語","membaca＝読む"]),

  q("READ-A021","読解","★★☆","Ayah mencuci mobil di depan rumah.","父はどこで車を洗いますか？",["家の前","家の中","学校の前","市場"],"家の前","アヤ ムンチュチ モビル ディ ドゥパン ルマ","di depan rumah＝家の前","場所表現 di depan に注目です。",{"家の中":"di dalam rumah です。","学校の前":"di depan sekolah です。","市場":"pasar です。"},["mencuci＝洗う","mobil＝車"]),
  q("READ-A022","読解","★★★","Kucing tidur di bawah meja.","猫はどこで寝ていますか？",["机の下","机の上","椅子の上","家の外"],"机の下","クチン ティドゥル ディ バワ メジャ","di bawah meja＝机の下","di bawah は『〜の下』です。",{"机の上":"di atas meja です。","椅子の上":"di atas kursi です。","家の外":"di luar rumah です。"},["kucing＝猫","tidur＝寝る"]),
  q("READ-A023","読解","★★☆","Saya jarang minum kopi.","私はどのくらいコーヒーを飲みますか？",["めったに飲まない","いつも飲む","よく飲む","一度も飲まない"],"めったに飲まない","サヤ ジャラン ミヌム コピ","jarang＝めったに〜ない","頻度表現の問題です。",{"いつも飲む":"selalu です。","よく飲む":"sering です。","一度も飲まない":"tidak pernah です。"},["jarang＝めったに〜ない","kopi＝コーヒー"]),
  q("READ-A024","読解","★★☆","Mereka selalu datang tepat waktu.","彼らはどのくらい時間通りに来ますか？",["いつも","ときどき","めったにない","一度もない"],"いつも","ムレカ スラル ダタン トゥパット ワクトゥ","selalu＝いつも","頻度が最も高い表現です。",{"ときどき":"kadang-kadang です。","めったにない":"jarang です。","一度もない":"tidak pernah です。"},["tepat waktu＝時間通り","datang＝来る"]),
  q("READ-A025","読解","★★★","Saya membeli dua buah apel.","私はりんごをいくつ買いましたか？",["2個","2人","2匹","2枚"],"2個","サヤ ムンブリ ドゥア ブア アペル","dua buah apel＝2個のりんご","buah は物・果物用助数詞です。",{"2人":"dua orang です。","2匹":"dua ekor です。","2枚":"dua lembar です。"},["buah＝物・果物用","apel＝りんご"]),

  q("READ-A026","読解","★★☆","Ada tiga orang guru di sekolah.","学校に先生は何人いますか？",["3人","3匹","3個","3枚"],"3人","アダ ティガ オラン グル ディ スコラ","tiga orang guru＝3人の先生","orang は人用助数詞です。",{"3匹":"tiga ekor です。","3個":"tiga buah です。","3枚":"tiga lembar です。"},["guru＝先生","orang＝人用"]),
  q("READ-A027","読解","★★☆","Saya melihat empat ekor burung.","私は鳥を何羽見ましたか？",["4羽","4人","4枚","4月"],"4羽","サヤ ムリハット ウンパット エコール ブルン","empat ekor burung＝4羽の鳥","ekor は動物用助数詞です。",{"4人":"empat orang です。","4枚":"empat lembar です。","4月":"April です。"},["burung＝鳥","ekor＝動物用"]),
  q("READ-A028","読解","★★★","Besok saya pergi ke rumah nenek.","私は明日どこへ行きますか？",["祖母の家","学校","市場","病院"],"祖母の家","ベソッ サヤ プルギ ク ルマ ネネッ","rumah nenek＝祖母の家","besok は明日、ke は〜へです。",{"学校":"sekolah です。","市場":"pasar です。","病院":"rumah sakit です。"},["besok＝明日","nenek＝祖母"]),
  q("READ-A029","読解","★★☆","Kemarin dia bekerja di bank.","彼・彼女は昨日どこで働きましたか？",["銀行","学校","病院","薬局"],"銀行","クマリン ディア ブクルジャ ディ バンク","bank＝銀行","di bank は『銀行で』です。",{"学校":"sekolah です。","病院":"rumah sakit です。","薬局":"apotik です。"},["kemarin＝昨日","bekerja＝働く"]),
  q("READ-A030","読解","★★★","Saya tidak suka makanan pedas.","私はどんな食べ物が好きではありませんか？",["辛い食べ物","甘い食べ物","冷たい飲み物","温かい飲み物"],"辛い食べ物","サヤ ティダッ スカ マカナン プダス","makanan pedas＝辛い食べ物","tidak suka は『好きではない』です。",{"甘い食べ物":"makanan manis です。","冷たい飲み物":"minuman dingin です。","温かい飲み物":"minuman hangat です。"},["pedas＝辛い","makanan＝食べ物"])
);
